---
- name: create a instance
  google.cloud.gcp_sql_instance:
    name: "{{master_db_name}}"
    settings:
      ip_configuration:
        authorized_networks:
        - name: google dns server
          value: 8.8.8.8/32
      tier: "{{ machine_tier }}"
      backup_configuration:
        binary_log_enabled: yes
        enabled: yes
      availability_type: "REGIONAL"
    backend_type: "SECOND_GEN"
    database_version: "MYSQL_5_7"
    max_disk_size: "{{ max_disk_storage }}"
    region: "{{ master_db_region }}"
    project: "{{ project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ credentials_file }}"
    state: present
  register: instance
  tags:
    - create_master_instance

- name: create a database
  google.cloud.gcp_sql_database:
    name: "{{ DB_NAME }}"
    charset: utf8
    instance: "{{ master_db_name }}"
    project: "{{ project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ credentials_file }}"
    state: present
  tags:
    - create_database

- name: create a user
  google.cloud.gcp_sql_user:
    name: "{{ DB_USER }}"
    host: "{{ DB_HOST }}"
    password: "{{ DB_PASS }}"
    instance: "{{ instance }}"
    project: "{{ project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ credentials_file }}"
    state: present
  tags:
    - create_user
