---
- name: destroy master instance
  google.cloud.gcp_sql_instance:
    name: "{{ item }}"
    project: "{{ project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ credentials_file }}"
    state: absent
  loop: "{{ replicas }}"




