---
- name: destroy db
  tags: destroy_db
  google.cloud.gcp_sql_database:
    instance: "{{master_db_name}}"
    name: "wikijs_db"
    project: "{{ project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ credentials_file }}"
    state: absent

- name: destroy master instance
  tags: destroy_master_instance
  google.cloud.gcp_sql_instance:
    name: "{{master_db_name}}"
    project: "{{ project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ credentials_file }}"
    state: absent



