---
- name: pull wikijs image
  docker_image:
    name: "{{ image }}"
    source: pull

- name: Create kubectl config
  command: gcloud container clusters get-credentials k8s-wikijs --zone europe-west2-a --project ascn-tp-336100

#- name: Install kubectl
#  command: gcloud components install kubectl

- name: Create a k8s namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ namespace }}"

- name: Change context
  command: kubectl config set-context --current --namespace=wikijs

- name: Create secret
  command: kubectl create secret generic cloudsql-db-1 --from-file=service_account.json=./service-account.json

- name: Create k8s pod for wikijs
  tags: deploy_pods
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Deployment
      metadata:
        name: "{{ app }}"
        namespace: "{{ namespace }}"
      spec:
        selector:
          matchLabels:
            run: balancer
        replicas: 1
        template:
          metadata:
            labels:
              run: balancer
          spec:
            containers:
              - name: "{{ app }}"
                image: "{{ image }}"
                imagePullPolicy: Always
                env:
                  - name: DB_TYPE
                    value: "{{ DB_TYPE }}"
                  - name: DB_HOST
                    value: "localhost"
                  - name: DB_PORT
                    value: "{{ DB_PORT }}"
                  - name: DB_USER
                    value: "{{ DB_USER }}"
                  - name: DB_PASS
                    value: "{{ DB_PASS }}"
                  - name: DB_NAME
                    value: "{{ DB_NAME }}"
              - name: cloud-sql-proxy
                image: gcr.io/cloudsql-docker/gce-proxy:latest
                command: ["/cloud_sql_proxy", "-instances={{ project_id }}:{{ region }}:{{ master_db_name }}=tcp:{{ DB_PORT }}", "-credential_file=/secrets/service_account.json"]
                securityContext:
                    runAsNonRoot: true
                volumeMounts:
                    - name: cloudsql-db-1
                      mountPath: /secrets/
                      readOnly: true
            volumes:
            - name: cloudsql-db-1
              secret:
                defaultMode: 511
                secretName: cloudsql-db-1

- name: Expose service
  tags: expose_service
  command: kubectl expose deployment wikijs --type=LoadBalancer --name=servico --port 80 --target-port 3000 


